### ISSUE TITLE
import Config object

### ISSUE THREAD

**Issue by GryfonN** [react-webpack-generators/generator-react-webpack#191] opened 2016-02-18 21:23 UTC
Hi I want to report mistake in /src/config/README.md

if you load module with `let config = require('config');` then you have to use **default** property `let currentAppEnv = config.default.appEnv;` and not just `let currentAppEnv = config.appEnv;`

But if you will import confi module with `import config from 'config';` everything is fine

**Comment by weblogixx** [comment] 2016-02-19 07:37
@GryfonN: Thanks for pointing this out. This is true because we export the default property and it will not be available directly when using webpack requires. I would recommend using the import syntax, but your milage may vary.

However I will have a look at this.

**Comment by GryfonN** [comment] 2016-02-19 10:44
No problem, thanks for quick response.

**Comment by sthzg** [comment] 2016-08-11 12:54
I am certainly late to this issue 😄 . This is certainly a regression after updating from Babel 5 to 6 (a quite common one). We could either path our setup with [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) (+11k downloads in the last day) or let it be a like that for that awkward transitioning phase towards ES2015. In that case I would update the README in `src/config/README.md`.

**Comment by sthzg** [comment] 2016-08-17 14:22
To avoid the extra dependency mentioned above, I've just updated the README in the `master` and `2.x` branch of the template repository (however, anyone using Common JS will be likely installing `babel-plugin-add-moudle-exports` on their own sooner or later and then being able to drop the `.default`).

Closing this for now. Feel free to re-open it if there are issues.

**Closed by sthzg** 2016-08-17 14:22 UTC
Labels: bug
