### ISSUE TITLE
Running app generator does not create project scaffold

### ISSUE THREAD

**Issue by loosenRogers** [react-webpack-generators/generator-react-webpack#271] opened 2016-08-11 14:19 UTC
when iI follow the introduction to generate my project, here comes the error.
my command:"yo react-webpack galleyReact",i want to use react-webpack to generate a project named "galleryReact",then
? Please choose your application name (galleryReact)

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\node_modules\yeoman-generator\lib\base.js:240:45)
    at module.exports.generator.Base.extend.prompting (C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\generators\app\index.js:40:10)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\node_modules\yeoman-generator\lib\base.js:439:23)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\node_modules\yeoman-generator\node_modules\run-async\index.js:26:25
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\node_modules\yeoman-generator\node_modules\run-async\index.js:25:19
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\generator-react-webpack\node_modules\yeoman-generator\lib\base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

i have no idea of solving this problem,hoping you can give some help,thanks!

**Comment by sthzg** [comment] 2016-08-11 15:12
@loosenRogers can you post which version of the yo cli you are using? `yo --version` on the command line should output the version number (do the steps in this [SO question](http://stackoverflow.com/questions/37193740/error-unhandled-error-event-after-running-yo-generator) solve the issue?)

**Comment by loosenRogers** [comment] 2016-08-12 00:40
the version of the yo cli is 1.5.1

**Comment by loosenRogers** [comment] 2016-08-12 01:29
i update my yo version to 1.8.4 ,then i try generate the project again.
This is the result:
Out of the box I include Webpack and some default React components.

? Please choose your application name (galleryReact) galleryReact
? Please choose your application name galleryReact
? Which style language do you want to use? (Use arrow keys)
? Which style language do you want to use? sass
? Enable postcss? (y/N) y
? Enable postcss? Yes
But i found there was no project generated.

**Comment by FamiliarPie** [comment] 2016-08-12 07:14
I was having this exact same error, but it appears installing directly from using npm seemed to resolve the issue for me. 
`npm uninstall -g generator-react-webpack`
`npm install -g https://github.com/react-webpack-generators/generator-react-webpack.git`

**Comment by sthzg** [comment] 2016-08-12 08:13
@loosenRogers @FamiliarPie hi guys, thanks for reporting. I can reproduce the problem on my local machine. There were quite a bit of changes in the past days, both in terms of code and infrastructure (e.g. moving the repository url of this generator), so maybe some wires got crossed along the way. Sorry that you run into these problems, we'll look into it right away.

**Comment by sthzg** [comment] 2016-08-12 08:54
Okay, the reason is due to the updated dependency to `yeoman-generator 0.24`, which moved over to a newer version to inquirer.js that started moving to promises (and thus deprecates the `var done = this.async()` api). Fix is coming in the next minutes.

**Comment by sthzg** [comment] 2016-08-12 09:29
Thanks again for reporting, this fix will be available through `npm` with the next releasee of the generator. I am leaving this ticket open as a reminder until the package is published.

**Comment by weblogixx** [comment] 2016-08-12 10:47
Sorry, this was my fault :(. It seems I did not run tests before publishing the actual v3 stable.
@sthzg: Sorry you had to step in, great work as always! Thank you! You may publish any time, npm permissions are set up accordingly.

**Comment by sthzg** [comment] 2016-08-12 11:09
@weblogixx no worries, I fixed exactly the same issue a short while ago on another gist, so I already had an idea about where it is coming from.

New patch release [v3.3.4](https://github.com/react-webpack-generators/generator-react-webpack/releases/tag/v3.3.4) is published on npm.

**Closed by sthzg** 2016-08-12 11:09 UTC
Labels: bug

**Comment by acwonders** [comment] 2016-08-12 13:57
I had the exactly same issue yesterday on v3.3.3. Just tried with v3.3.4 and the issue is gone. Thanks!

**Comment by sthzg** [comment] 2016-08-12 14:07
@acwonders 🙇  thanks for testing the update and taking your time to confirm the fix.
